# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eduhacks2017' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod "ROGoogleTranslate"

  # Pods for eduhacks2017

end
